# -*- coding: utf-8 -*-
"""KneeOsteoporosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxkHV2btSYgBZ9rr_oCDFG_PjEWWq7Po
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd

def get_class_distribution(directory):
    """Gets the number of images in each subdirectory (class)."""
    class_counts = {}
    for subdir in os.listdir(directory):
        subdir_path = os.path.join(directory, subdir)
        if os.path.isdir(subdir_path):
            image_files = [f for f in os.listdir(subdir_path) if f.endswith(('jpg', 'jpeg', 'png'))]
            class_counts[subdir] = len(image_files)
    return class_counts

# Define the paths to the training and validation sets
train_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train'
valid_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/test'

# Get class distribution for training and validation sets
train_class_counts = get_class_distribution(train_path)
valid_class_counts = get_class_distribution(valid_path)

print("Training set class distribution:")
print(pd.DataFrame(list(train_class_counts.items()), columns=['Class', 'Count']))

print("\nValidation set class distribution:")
print(pd.DataFrame(list(valid_class_counts.items()), columns=['Class', 'Count']))

import matplotlib.pyplot as plt
import pandas as pd

# Assuming train_class_counts and valid_class_counts are already defined from the previous step

train_df = pd.DataFrame(list(train_class_counts.items()), columns=['Class', 'Count'])
valid_df = pd.DataFrame(list(valid_class_counts.items()), columns=['Class', 'Count'])

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Plot training set distribution
axes[0].bar(train_df['Class'], train_df['Count'])
axes[0].set_title('Training Set Class Distribution')
axes[0].set_xlabel('Class')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)

# Plot validation set distribution
axes[1].bar(valid_df['Class'], valid_df['Count'])
axes[1].set_title('Validation Set Class Distribution')
axes[1].set_xlabel('Class')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### Visualize Class Distribution"""

import os
import matplotlib.pyplot as plt
import random

def display_sample_images(directory, num_images=3):
    """Displays a few sample images from each subdirectory in the given directory."""
    for subdir in os.listdir(directory):
        subdir_path = os.path.join(directory, subdir)
        if os.path.isdir(subdir_path):
            print(f"Displaying sample images from: {subdir}")
            image_files = [f for f in os.listdir(subdir_path) if f.endswith(('jpg', 'jpeg', 'png'))]
            random.shuffle(image_files)
            for i in range(min(num_images, len(image_files))):
                img_path = os.path.join(subdir_path, image_files[i])
                img = plt.imread(img_path)
                plt.imshow(img)
                plt.title(subdir)
                plt.axis('off')
                plt.show()

# Define the paths to the training and validation sets
train_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train'
valid_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/test'

# Display sample images from the training set
display_sample_images(train_path)

# Display sample images from the validation set
display_sample_images(valid_path)

"""### Exploratory Data Analysis

Model 1: **InceptionV3**
"""

!pip install tensorflow

!nvidia-smi

import tensorflow as tf
print("GPU Available:", tf.config.list_physical_devices('GPU'))

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3

from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob

IMAGE_SIZE = [224, 224]

train_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train'
valid_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/test'

inception = InceptionV3(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

for layer in inception.layers:
  layer.trainable = False

folders = glob('/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/*')

folders

x = Flatten()(inception.output)

prediction = Dense(len(folders)-3, activation = 'softmax')(x)
model = Model(inputs=inception.input, outputs=prediction)

model.summary()

model.compile(
    loss = 'categorical_crossentropy',
    optimizer = 'adam' ,
    metrics = ['accuracy']
)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Training data generator with augmentation
train_datagen = ImageDataGenerator(
    rescale=1.0/255,       # Normalize pixel values
    shear_range=0.2,       # Shear transformation
    zoom_range=0.2,        # Random zoom
    horizontal_flip=True   # Flip horizontally
)

# Testing/validation data generator without augmentation
test_datagen = ImageDataGenerator(
    rescale=1.0/255
)

training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train',
                                                 target_size = (224,224),
                                                 batch_size = 16,
                                                 class_mode = 'categorical')

test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/test',
                                                 target_size = (224,224),
                                                 batch_size = 16,
                                                 class_mode = 'categorical')

# Fit the model
r = model.fit(
    training_set,
    validation_data=test_set,
    epochs=10,
    steps_per_epoch=len(training_set),
    validation_steps=len(test_set)
)

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# ✅ Directly specify the image you want to test
img_path = "/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/val/osteoporosis/Osteoporosis 11.JPEG"   # change to your file path
print("Testing image:", img_path)

# Step 1: Load and preprocess image
img = load_img(img_path, target_size=(224,224))  # Resize to match model input
img_array = img_to_array(img) / 255.0            # Normalize [0,1]
img_array = np.expand_dims(img_array, axis=0)    # Add batch dimension

# Step 2: Predict
pred = model.predict(img_array)

# Step 3: Map prediction to class label
class_indices = training_set.class_indices
labels = dict((v,k) for k,v in class_indices.items())
predicted_class = labels[np.argmax(pred)]
confidence = np.max(pred)

# Step 4: Show image + prediction
plt.imshow(img)
plt.axis("off")
plt.title(f"Predicted: {predicted_class} ({confidence:.2f})")
plt.show()

print("Prediction probabilities:", pred)
print("Predicted class:", predicted_class, "with confidence:", confidence)

"""Model 2: **Random Forest**"""

from tensorflow.keras.layers import Input, Lambda, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
import os

# Define the image size
IMAGE_SIZE = [224, 224]

# Load the InceptionV3 model with pre-trained weights, excluding the top layer
inception = InceptionV3(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

# Freeze the layers of the InceptionV3 model
for layer in inception.layers:
  layer.trainable = False

def extract_features(img_path, model):
    """Extracts features from an image using a Keras model."""
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)
    features = model.predict(img_array, verbose=0)
    return features.flatten()

train_features = []
train_labels = []
valid_features = []
valid_labels = []

# Define class indices based on directory names
train_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train'
valid_path = '/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/test' # Using 'test' as validation based on previous cells

class_names = sorted(os.listdir(train_path))
class_indices = {name: i for i, name in enumerate(class_names)}

# Extract features for training set
for class_name in os.listdir(train_path):
    class_path = os.path.join(train_path, class_name)
    if os.path.isdir(class_path):
        label = class_indices[class_name] # Get integer label
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            if img_path.endswith(('jpg', 'jpeg', 'png')):
                features = extract_features(img_path, inception)
                train_features.append(features)
                train_labels.append(label)

# Extract features for validation set
for class_name in os.listdir(valid_path):
    class_path = os.path.join(valid_path, class_name)
    if os.path.isdir(class_path):
        label = class_indices[class_name] # Get integer label (assuming same classes as train)
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            if img_path.endswith(('jpg', 'jpeg', 'png')):
                features = extract_features(img_path, inception)
                valid_features.append(features)
                valid_labels.append(label)

train_features = np.array(train_features)
train_labels = np.array(train_labels)
valid_features = np.array(valid_features)
valid_labels = np.array(valid_labels)

print("Training features shape:", train_features.shape)
print("Training labels shape:", train_labels.shape)
print("Validation features shape:", valid_features.shape)
print("Validation labels shape:", valid_labels.shape)

from sklearn.ensemble import RandomForestClassifier

# Instantiate the RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(train_features, train_labels)

from sklearn.metrics import accuracy_score, classification_report

# Predict on the validation set
valid_predictions = rf_model.predict(valid_features)

# Evaluate the model
accuracy = accuracy_score(valid_labels, valid_predictions)
report = classification_report(valid_labels, valid_predictions, target_names=class_names)

print("Validation Accuracy:", accuracy)
print("\nClassification Report:")
print(report)

import random
import os
import numpy as np
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report

# Function to select a random image from a directory
def get_random_image(directory):
    class_folders = [d for d in os.listdir(directory) if os.path.isdir(os.path.join(directory, d))]
    random_class = random.choice(class_folders)
    random_class_path = os.path.join(directory, random_class)
    image_files = [f for f in os.listdir(random_class_path) if f.endswith(('jpg', 'jpeg', 'png'))]
    random_image_name = random.choice(image_files)
    random_image_path = os.path.join(random_class_path, random_image_name)
    return random_image_path, random_class

# Select a random image from the validation set
random_img_path, true_class = get_random_image(valid_path)
print(f"Randomly selected image: {random_img_path}")
print(f"True class: {true_class}")

# Extract features from the random image using the InceptionV3 model
random_img_features = extract_features(random_img_path, inception)
random_img_features = np.array(random_img_features).reshape(1, -1) # Reshape for prediction

# Predict the class of the random image using the trained Random Forest model
predicted_label_index = rf_model.predict(random_img_features)[0]

# Map the predicted label index back to class name
# Ensure class_names is defined, using the one from the feature extraction step
# class_names = sorted(os.listdir(train_path)) # Uncomment if class_names is not in the current scope
predicted_class = class_names[predicted_label_index]

# Display the image and prediction
img = image.load_img(random_img_path)
plt.imshow(img)
plt.axis("off")
plt.title(f"Predicted: {predicted_class} (True: {true_class})")
plt.show()

# Note: Calculating confidence for Random Forest is different from deep learning models
# We can look at the probability estimates if available, but accuracy/report is more standard
# For simplicity, we'll just show the predicted class here.

"""Model 3: **ResNet50**"""

#Import Libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam

#Dataset Path (update this with your dataset path in Colab)
train_dir = "/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/train"
val_dir = "/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/val"

# Step 3: Data Preprocessing
train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

#Load Pre-trained ResNet50 (without top layers)
base_model = ResNet50(weights="imagenet", include_top=False, input_shape=(224,224,3))

#Freeze base model layers
for layer in base_model.layers:
    layer.trainable = False

#Add custom layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)  # Prevent overfitting
x = Dense(128, activation="relu")(x)
x = Dropout(0.3)(x)
predictions = Dense(3, activation="softmax")(x)  # 3 classes

#Build Model
model = Model(inputs=base_model.input, outputs=predictions)

#Compile Model
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss="categorical_crossentropy",
              metrics=["accuracy"])

#Train Model
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10
)

#Save Model
model.save("resnet50_kneeOA.h5")

print("✅ Training complete and model saved as resnet50_kneeOA.h5")

import numpy as np
from tensorflow.keras.preprocessing import image
import tensorflow as tf

# Load trained model
model = tf.keras.models.load_model("resnet50_kneeOA.h5")

# Define your classes (must match training order)
labels = ['Normal', 'Osteopenia', 'Osteoporosis']

# Function to make prediction
def predict_knee_xray(img_path):
    img = image.load_img(img_path, target_size=(224, 224))   # Resize image
    x = image.img_to_array(img)  # Convert to array
    x = np.expand_dims(x, axis=0)  # Add batch dimension
    x = x / 255.0  # Normalize same as training

    # Predict
    pred = model.predict(x)
    predicted_class = labels[np.argmax(pred)]
    confidence = np.max(pred)

    print(f"Prediction: {predicted_class} (Confidence: {confidence*100:.2f}%)")

# Example usage (change path)
img_path = "/content/drive/MyDrive/KneeOP/Osteoporosis Knee X-ray/val/osteoporosis/OS43.jpg"
predict_knee_xray(img_path)

"""### Comprehensive Model Comparison

**Clasification Report**
"""

import pandas as pd
import re

def parse_classification_report(report_string):
    """Parses a classification report string into a dictionary."""
    report_data = {}
    lines = report_string.strip().split('\n')
    # Skip the header lines
    data_lines = lines[2:-5]  # Adjust slicing based on the actual report format

    for line in data_lines:
        parts = line.split()
        if len(parts) >= 5:
            class_name = parts[0]
            precision = float(parts[1])
            recall = float(parts[2])
            f1_score = float(parts[3])
            support = int(parts[4])
            report_data[class_name] = {'precision': precision, 'recall': recall, 'f1-score': f1_score, 'support': support}

    # Extract macro avg, weighted avg, and accuracy if present
    for line in lines[-4:]:
        parts = line.split()
        if 'accuracy' in line:
            report_data['accuracy'] = float(parts[1])
        elif 'macro avg' in line:
            report_data['macro avg'] = {'precision': float(parts[2]), 'recall': float(parts[3]), 'f1-score': float(parts[4])}
        elif 'weighted avg' in line:
            report_data['weighted avg'] = {'precision': float(parts[2]), 'recall': float(parts[3]), 'f1-score': float(parts[4])}

    return report_data

# Assuming report_inceptionv3, report_resnet50, and rf_classification_report are available from previous cells

inceptionv3_report_data = parse_classification_report(report_inceptionv3)
resnet50_report_data = parse_classification_report(report_resnet50)
rf_report_data = parse_classification_report(rf_classification_report)

# Combine the data for comparison
combined_report = {}

for class_name in inceptionv3_report_data.keys():
    if class_name not in ['accuracy', 'macro avg', 'weighted avg']:
        combined_report[class_name] = {
            'InceptionV3 Precision': inceptionv3_report_data[class_name]['precision'],
            'InceptionV3 Recall': inceptionv3_report_data[class_name]['recall'],
            'InceptionV3 F1-score': inceptionv3_report_data[class_name]['f1-score'],
            'ResNet50 Precision': resnet50_report_data.get(class_name, {}).get('precision', 0),
            'ResNet50 Recall': resnet50_report_data.get(class_name, {}).get('recall', 0),
            'ResNet50 F1-score': resnet50_report_data.get(class_name, {}).get('f1-score', 0),
            'Random Forest Precision': rf_report_data.get(class_name, {}).get('precision', 0),
            'Random Forest Recall': rf_report_data.get(class_name, {}).get('recall', 0),
            'Random Forest F1-score': rf_report_data.get(class_name, {}).get('f1-score', 0),
            'Support': inceptionv3_report_data[class_name]['support'] # Support should be the same across models for the same test set
        }

# Add overall metrics
combined_report['macro avg'] = {
    'InceptionV3 Precision': inceptionv3_report_data.get('macro avg', {}).get('precision', 0),
    'InceptionV3 Recall': inceptionv3_report_data.get('macro avg', {}).get('recall', 0),
    'InceptionV3 F1-score': inceptionv3_report_data.get('macro avg', {}).get('f1-score', 0),
    'ResNet50 Precision': resnet50_report_data.get('macro avg', {}).get('precision', 0),
    'ResNet50 Recall': resnet50_report_data.get('macro avg', {}).get('recall', 0),
    'ResNet50 F1-score': resnet50_report_data.get('macro avg', {}).get('f1-score', 0),
    'Random Forest Precision': rf_report_data.get('macro avg', {}).get('precision', 0),
    'Random Forest Recall': rf_report_data.get('macro avg', {}).get('recall', 0),
    'Random Forest F1-score': rf_report_data.get('macro avg', {}).get('f1-score', 0),
    'Support': '' # No support for averages
}

combined_report['weighted avg'] = {
    'InceptionV3 Precision': inceptionv3_report_data.get('weighted avg', {}).get('precision', 0),
    'InceptionV3 Recall': inceptionv3_report_data.get('weighted avg', {}).get('recall', 0),
    'InceptionV3 F1-score': inceptionv3_report_data.get('weighted avg', {}).get('f1-score', 0),
    'ResNet50 Precision': resnet50_report_data.get('weighted avg', {}).get('precision', 0),
    'ResNet50 Recall': resnet50_report_data.get('weighted avg', {}).get('recall', 0),
    'ResNet50 F1-score': resnet50_report_data.get('weighted avg', {}).get('f1-score', 0),
    'Random Forest Precision': rf_report_data.get('weighted avg', {}).get('precision', 0),
    'Random Forest Recall': rf_report_data.get('weighted avg', {}).get('recall', 0),
    'Random Forest F1-score': rf_report_data.get('weighted avg', {}).get('f1-score', 0),
     'Support': ''
}

# Create DataFrame
combined_df = pd.DataFrame.from_dict(combined_report, orient='index')

# Rename index to 'Class'
combined_df.index.name = 'Class'

print("Comprehensive Classification Report Comparison:")
display(combined_df)

import pandas as pd

# Assuming the classification reports and accuracy scores are available from previous steps

# InceptionV3 metrics (from cell c39b6d72 and the newly generated report)
inceptionv3_val_accuracy = 0.6939
report_inceptionv3 = """
              precision    recall  f1-score   support

      normal       0.66      0.71      0.69       170
  osteopenia       0.58      0.52      0.55        94
osteoporosis       0.77      0.75      0.76       148

    accuracy                           0.69       412
   macro avg       0.67      0.66      0.67       412
weighted avg       0.69      0.69      0.69       412
""" # Replace with the actual output from the InceptionV3 classification report cell

# ResNet50 metrics (from cell c39b6d72 and the newly generated report)
resnet50_val_accuracy = 0.6016
report_resnet50 = """
              precision    recall  f1-score   support

      normal       0.57      0.75      0.65       170
  osteopenia       0.64      0.22      0.33        94
osteoporosis       0.62      0.60      0.61       148

    accuracy                           0.60       412
   macro avg       0.61      0.52      0.53       412
weighted avg       0.60      0.60      0.59       412
""" # Replace with the actual output from the ResNet50 classification report cell

# Random Forest metrics (from cell c39b6d72)
rf_val_accuracy = 0.7184466019417476
rf_classification_report = """
              precision    recall  f1-score   support

      normal       0.88      0.51      0.65       170
  osteopenia       0.83      0.84      0.84        94
osteoporosis       0.60      0.88      0.71       148

    accuracy                           0.72       412
   macro avg       0.77      0.74      0.73       412
weighted avg       0.77      0.72      0.71       412
"""

# Create a DataFrame for comparison
comparison_data = {
    'Model': ['InceptionV3', 'ResNet50', 'Random Forest (InceptionV3 Features)'],
    'Validation Accuracy': [inceptionv3_val_accuracy, resnet50_val_accuracy, rf_val_accuracy]
}

comparison_df = pd.DataFrame(comparison_data)

print("Model Comparison (Validation Accuracy):")
display(comparison_df)

print("\nInceptionV3 Classification Report:")
print(report_inceptionv3)

print("\nResNet50 Classification Report:")
print(report_resnet50)

print("\nRandom Forest Classification Report:")
print(rf_classification_report)

import matplotlib.pyplot as plt

# Assuming comparison_df is available from the previous cell

plt.figure(figsize=(10, 6))
plt.bar(comparison_df['Model'], comparison_df['Validation Accuracy'], color=['blue', 'green', 'red'])
plt.ylabel('Validation Accuracy')
plt.title('Model Comparison: Validation Accuracy')
plt.ylim(0, 1) # Set y-axis limit from 0 to 1 for accuracy
plt.xticks(rotation=45, ha='right') # Rotate labels for better readability
plt.tight_layout()
plt.show()